### PR TITLE
Made it all better

### PR DESCRIPTION
**Pull request by diegovb**

### CODE REVIEW

**Comment by fmenozzi** [comment]
Not destructive enough. Perhaps you could send a virus to all my email contacts too?

**Comment by diegovb** [comment]
I'm going to need your contact list then.

**Comment by fmenozzi** [comment]
I'll just leave my email credentials.

username: fmenozzi@secure.com
password: hunter2

**Comment by fmenozzi** [comment]
HEY

**Comment by fmenozzi** [comment]
You don't get to close my issues

**Pull request closed without merging**
